### ISSUE TITLE
Uninitialized constant (OpenSSL)

### ISSUE THREAD

**Issue by jcronk** [h6y3/todoist-ruby#3]
It looks like in todoist/util/network_helper.rb, it needs a `require 'openssl'` to work.  I'm getting an error when I try the `@client.misc_quick.add_item("my item")`, and adding the "require" seemed to fix it.  I'll create a pull request if you want, but this seemed like a pretty simple fix.

**Comment by jcronk** [comment]
This error, specifically, is what I'm talking about:

```
Traceback (most recent call last):
        6: from /usr/local/bin/irb:11:in `<main>'
        5: from (irb):7
        4: from /usr/local/lib/ruby/gems/2.5.0/gems/todoist-ruby-0.2.1/lib/todoist/misc/quick.rb:9:in `add_item'
        3: from /usr/local/lib/ruby/gems/2.5.0/gems/todoist-ruby-0.2.1/lib/todoist/util/api_helper.rb:71:in `get_response'
        2: from /usr/local/lib/ruby/gems/2.5.0/gems/todoist-ruby-0.2.1/lib/todoist/util/network_helper.rb:54:in `get_response'
        1: from /usr/local/lib/ruby/gems/2.5.0/gems/todoist-ruby-0.2.1/lib/todoist/util/network_helper.rb:25:in `configure_http'
NameError (uninitialized constant Todoist::Util::NetworkHelper::OpenSSL)
```

**Comment by h6y3** [comment]
Thanks!  I'll fix it.  Strange that I missed this in my unit tests.
